export type GhanaRegionOption = {
  name: string
  towns: string[]
}

export type IndustryOption = {
  name: string
}

export type BankOption = {
  name: string
}

export const ghanaRegions: GhanaRegionOption[] = [
  {
    name: "Ahafo",
    towns: [
      "Goaso",
      "Kenyasi",
      "Mim",
      "Hwidiem",
      "Kukuom",
      "Sankore",
      "Duayaw Nkwanta",
      "Acherensua",
      "Hwidiem",
      "Dadiesoaba",
    ],
  },
  {
    name: "Ashanti",
    towns: [
      "Kumasi",
      "Obuasi",
      "Ejisu",
      "Bekwai",
      "Konongo",
      "Mampong",
      "Agogo",
      "Nsuta",
      "Asante Mampong",
      "New Edubiase",
    ],
  },
  {
    name: "Bono",
    towns: [
      "Sunyani",
      "Berekum",
      "Wenchi",
      "Dormaa Ahenkro",
      "Techiman",
      "Nkoranza",
      "Jaman North",
      "Banda Ahenkro",
      "Duayaw Nkwanta",
      "Sampa",
    ],
  },
  {
    name: "Bono East",
    towns: [
      "Techiman",
      "Kintampo",
      "Atebubu",
      "Nkoranza",
      "Prang",
      "Yeji",
      "Jema",
      "Aframso",
      "Kyeremasu",
      "Sekyedumase",
    ],
  },
  {
    name: "Central",
    towns: [
      "Cape Coast",
      "Elmina",
      "Kasoa",
      "Winneba",
      "Mankessim",
      "Swedru",
      "Saltpond",
      "Apam",
      "Dunkwa-on-Offin",
      "Agona Swedru",
    ],
  },
  {
    name: "Eastern",
    towns: [
      "Koforidua",
      "Nkawkaw",
      "Suhum",
      "Akosombo",
      "Akyem Oda",
      "Somanya",
      "Nsawam",
      "Begoro",
      "Tafo",
      "Donkorkrom",
    ],
  },
  {
    name: "Greater Accra",
    towns: [
      "Accra",
      "Tema",
      "Madina",
      "Adenta",
      "Teshie",
      "Ashaiman",
      "Weija",
      "Abokobi",
      "Dodowa",
      "Kasoa",
    ],
  },
  {
    name: "North East",
    towns: [
      "Nalerigu",
      "Gambaga",
      "Walewale",
      "Bunkpurugu",
      "Langbinsi",
      "Chereponi",
      "Yagaba",
      "Sakogu",
      "Gbintiri",
      "Nakpanduri",
    ],
  },
  {
    name: "Northern",
    towns: [
      "Tamale",
      "Yendi",
      "Savelugu",
      "Gushiegu",
      "Karaga",
      "Saboba",
      "Tolon",
      "Kumbungu",
      "Bole",
      "Damongo",
    ],
  },
  {
    name: "Oti",
    towns: [
      "Dambai",
      "Jasikan",
      "Nkwanta",
      "Kadjebi",
      "Kete Krachi",
      "Krachi West",
      "Biakoye",
      "Kpassa",
      "Abotoase",
      "Ahamansu",
    ],
  },
  {
    name: "Savanna",
    towns: [
      "Damongo",
      "Buipe",
      "Salaga",
      "Daboya",
      "Sawla",
      "Bole",
      "Tuna",
      "Larabanga",
      "Busunu",
      "Mankarigu",
    ],
  },
  {
    name: "Upper East",
    towns: [
      "Bolgatanga",
      "Bawku",
      "Navrongo",
      "Paga",
      "Zebilla",
      "Sandema",
      "Garu",
      "Pusiga",
      "Tempane",
      "Fumbisi",
    ],
  },
  {
    name: "Upper West",
    towns: [
      "Wa",
      "Tumu",
      "Lawra",
      "Jirapa",
      "Nandom",
      "Gwollu",
      "Hamile",
      "Funsi",
      "Kaleo",
      "Dorimon",
    ],
  },
  {
    name: "Volta",
    towns: [
      "Ho",
      "Hohoe",
      "Keta",
      "Kpando",
      "Anloga",
      "Aflao",
      "Sogakope",
      "Dzodze",
      "Peki",
      "Denu",
    ],
  },
  {
    name: "Western",
    towns: [
      "Sekondi",
      "Takoradi",
      "Tarkwa",
      "Axim",
      "Prestea",
      "Bogoso",
      "Shama",
      "Enchi",
      "Half Assini",
      "Nsuaem",
    ],
  },
  {
    name: "Western North",
    towns: [
      "Sefwi Wiawso",
      "Bibiani",
      "Juaboso",
      "Enchi",
      "Dadieso",
      "Asankragua",
      "Bodi",
      "Chirano",
      "Akontombra",
      "Sefwi Bekwai",
    ],
  },
]

export const businessIndustries: IndustryOption[] = [
  { name: "Retail" },
  { name: "Wholesale" },
  { name: "Trading" },
  { name: "Manufacturing" },
  { name: "Agribusiness" },
  { name: "Construction" },
  { name: "Logistics" },
  { name: "Healthcare" },
  { name: "Hospitality" },
  { name: "Education" },
  { name: "Technology" },
  { name: "Professional Services" },
  { name: "Real Estate" },
  { name: "Finance" },
  { name: "Energy" },
  { name: "Telecommunications" },
  { name: "Media" },
  { name: "Transportation" },
]

export const ghanaBanks: BankOption[] = [
  { name: "Absa Bank Ghana" },
  { name: "Access Bank Ghana" },
  { name: "Agricultural Development Bank" },
  { name: "Bank of Africa Ghana" },
  { name: "CAL Bank" },
  { name: "Consolidated Bank Ghana" },
  { name: "Ecobank Ghana" },
  { name: "Fidelity Bank Ghana" },
  { name: "First Atlantic Bank" },
  { name: "First Bank Ghana" },
  { name: "GCB Bank" },
  { name: "Guaranty Trust Bank Ghana" },
  { name: "National Investment Bank" },
  { name: "Republic Bank Ghana" },
  { name: "Stanbic Bank Ghana" },
  { name: "Standard Chartered Bank Ghana" },
  { name: "Société Générale Ghana" },
  { name: "United Bank for Africa Ghana" },
  { name: "Zenith Bank Ghana" },
]

export function getTownOptions(regionName: string) {
  return ghanaRegions.find((region) => region.name === regionName)?.towns ?? []
}
